spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.A
spring.datasource.url=jdbc:sqlserver://<server>.database.windows.net:1433;database=<db>;user=<user>;password=<password>;
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
