spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.datasource.username=sa
spring.datasource.password=Secret1234
spring.datasource.url=jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=DB;